name: Generate Snake Animation 

on:
  schedule: # execute at midnight all days of week
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
    - main  


jobs:

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Snake Animation
      - name: generate snake grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push snake grid to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
